### ISSUE TITLE
[FR]: Load YouTube playlist

### ISSUE THREAD

**Issue by 1intan99** [PerformanC/NodeLink#23]
### Description

Loading the entire playlist out of non `/playlist?list=` URLs like:  `https://www.youtube.com/watch?v=K4DyBUG242c&list=PLW-S5oymMexXTgRyT3BWVt_y608nt85Uj`.

### Reason

Will be helpful if NodeLink can load the playlist from that url.

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Commited on NodeLink v2.
