### ISSUE TITLE
[BUG]: title is not defined (Sending play request with scsearch: )

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/NodeLink#24]
### NodeLink version

v2.0.0 (9e474e9)

### Description

This error occurs upon sending a play request while search is being done through the Soundcloud source.
Here is the error:
```js
10|NL      | ReferenceError: title is not defined
10|NL      |     at Object.search (file:///root/root/NodeLink/src/sources/soundcloud.js:183:71)
10|NL      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10|NL      |     at async Server.requestHandler (file:///root/root/NodeLink/src/connection/handler.js:396:27)
```

### Client

FastLink (a3158a8)

### Steps to reproduce

Send a play request to nodelink with scsearch:

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Fix landed on https://github.com/PerformanC/NodeLink/commit/8bb2e5ad85afe009457148f856c6dedb87c7dc1b.
