### ISSUE TITLE
[FR]: Bypassing Explicit Videos

### ISSUE THREAD

**Issue by clapann** [PerformanC/NodeLink#25]
### Description

Possibly allow us to provide YouTube credentials to bypass this or if there's any other possible way?

### Reason

Makes perfect sense to, and LL supports it. This will make user's able to play whatever music they'd like.

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Mind giving a try to https://github.com/PerformanC/NodeLink/commit/6a91ffe045df61293b7015afc77d4667b53412bd? Remember to enable `bypassAgeRestricted` on `config.js` file.
