### ISSUE TITLE
[BUG]: Loading Playlist causes SoundCloud error

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/NodeLink#26]
### NodeLink version

v2.0.0 (6a91ffe)

### Description

10|NL       | ReferenceError: data is not defined
10|NL       |     at Object.search (file:///root/root/NodeLink/src/sources/soundcloud.js:208:3)
10|NL       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10|NL       |     at async file:///root/root/NodeLink/src/sources/spotify.js:304:28

### Client

FastLink

### Steps to reproduce

Set default source to soundcloud
Use scsearch: to load a spotify playlist
The error comes up in console

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Fix landed on https://github.com/PerformanC/NodeLink/commit/f3d75613d25250e401e770e0a895d686d53b65b7, mind trying?

**Comment by TehPigYT** [comment]
Here is a new error from spotify this time.
![image](https://github.com/PerformanC/NodeLink/assets/34095153/97112dc6-7aaa-4826-883d-2fcbdba89940)

**Comment by ThePedroo** [comment]
Please create another issue. Thanks!
