### ISSUE TITLE
[BUG]: Loading Spotify Album causes an error

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/NodeLink#27]
### NodeLink version

v2.0.0 (1f6ddc7)

### Description

10|NL  | TypeError: Cannot read properties of undefined (reading 'images')
10|NL  |     at file:///root/root/NodeLink/src/sources/spotify.js:316:40
10|NL  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10|NL  | TypeError: Cannot read properties of undefined (reading 'images')
10|NL  |     at file:///root/root/NodeLink/src/sources/spotify.js:316:40
10|NL  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10|NL  | TypeError: Cannot read properties of undefined (reading 'images')
10|NL  |     at file:///root/root/NodeLink/src/sources/spotify.js:316:40
10|NL  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Client

FastLink

### Steps to reproduce

Connect to nodelink
Play a spotify album
The error will come up

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Fix landed on https://github.com/PerformanC/NodeLink/commit/42352db529c2ca53dee1429e47e8d973057097c0.
