### ISSUE TITLE
[BUG]: Playback of any track onlys lasts for max 10 seconds 

### ISSUE THREAD

**Issue by munishkhatri720** [PerformanC/NodeLink#29]
### NodeLink version

v2.0

### Description

I tried to play a track from SoundCloud, but the playback only lasts for a maximum of 10 seconds. Additionally, the sound cracks at intervals for 4-5 seconds.

Here are the logs: https://pastebin.mozilla.org/zqp6n6mh

### Client

Wavelink : 3.2.1
Node JS : 20.10.0

### Steps to reproduce

Play any Track with nodelink and after 10 second it will automatically loose connection . 

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Please re-run your logs with @performanc/voice from the GitHub for more clear logs

**Comment by ThePedroo** [comment]
Closing due to leak of further info.
