### ISSUE TITLE
[FR]: support youtu.be

### ISSUE THREAD

**Issue by 37dd** [PerformanC/NodeLink#33]
### Description

i can't use youtube url : youtu.be

### Reason

to make it easy to use

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Landed on https://github.com/PerformanC/NodeLink/commit/3802bb93032f5bfd33c2c2d4e12a26b83e378486.
