### ISSUE TITLE
[FR]: Wait x Milliseconds for startSpeakingEvent before sending Voice Websocket Data

### ISSUE THREAD

**Issue by clapann** [PerformanC/NodeLink#34]
### Description

Introduce a configuration setting that enables users to specify a delay before sending WebSocket data, awaiting a start-speaking event. This delay is designed to mitigate issues where a user's speech may be interrupted.

### Reason

I think this would be great, since sometimes Discord decides to cut out your audio completely, therefore resulting in 2 different audio buffers instead of a single one for a sentence.

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Landed on https://github.com/PerformanC/NodeLink/commit/9e37ba110707479f463bbc677d52cf37f5ded223.
