### ISSUE TITLE
[BUG]: "username is not defined" error upon loading a track from soundcloud

### ISSUE THREAD

**Issue by TehPigYT** [PerformanC/NodeLink#35]
### NodeLink version

5f130d4

### Description

```js
6|NL  | TypeError: Cannot read properties of undefined (reading 'username')
6|NL  |     at file:///root/root/NodeLink/src/sources/soundcloud.js:252:25
6|NL  |     at Array.forEach (<anonymous>)
6|NL  |     at Object.search (file:///root/root/NodeLink/src/sources/soundcloud.js:248:19)
6|NL  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
6|NL  |     at async Server.requestHandler (file:///root/root/NodeLink/src/connection/handler.js:388:20)
```

### Client

FastLink ([63d36b2](https://github.com/PerformanC/FastLink/commit/63d36b2e01938b10cb7eece33efd2ad0988a0d5e))

### Steps to reproduce

Set soundcloud as default search source
Use scsearch: to look for the track
The error shows up in console and prevents the bot from playing any actual audio.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Fix landed on https://github.com/PerformanC/NodeLink/commit/abe1eac9dec1bfef46f59cc26c5e7aae9b63528d.
