### ISSUE TITLE
[BUG]: trackEnd on "Live" type of requests

### ISSUE THREAD

**Issue by ZuherLaith** [PerformanC/NodeLink#41]
### NodeLink version

2.0.1

### Description

Upon trying to request "Lofi", a "Live" type of trackStarts with "0:00" length, after 3 seconds trackEnds instantly.

### Client

FastLink 2.4.2

### Steps to reproduce

Request "Lofi - Live" or any "Live" YT video, you'll see the problem.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Lives are not supported, I'll see about getting them implemented.

**Comment by ThePedroo** [comment]
It's easier to bypass this in client side by checking `isStream` field and ignoring that track
