### ISSUE TITLE
[BUG]: Live Stream is not beeing loaded even tho other streams work

### ISSUE THREAD

**Issue by Joniii11** [PerformanC/NodeLink#51]
### NodeLink version

2.0.1 (fdfaa8201ff7e7166a19a8ab0eb0ba8cd19dd84a)

### Description

When i try to load the stream for a radio station it just hangs itself up at loadTracks. I can see that it recieves the loadTracks from the client but just gets stuck. THere are no errors or anything.

```txt
0|NodeLink  | [loadtracks]: Received a request from client.
0|NodeLink  |  Params: "/v4/loadtracks"
0|NodeLink  |  Headers: {"host":"REDACTED","connection":"keep-alive","content-type":"application/json","authorization":"REDACTED","accept":"/","accept-language":"*","sec-fetch-mode":"cors","user-agent":"undici","accept-encoding":"gzip, deflate"}
0|NodeLink  | [loadTracks]: Loading track from https: https://dispatcher.rndfnk.com/br/br1/obb/mp3/mid
```

### Client

Modified Poru (latest version)

### Steps to reproduce

Load the stream: https://dispatcher.rndfnk.com/br/br1/obb/mp3/mid

### Example code

```ts
const searchedStation = {
      shortName: "Bayern",
      name: 'Bayern 1',
      stream: 'https://dispatcher.rndfnk.com/br/br1/obb/mp3/mid',
      logo: 'https://th.bing.com/th/id/OIP.BNZ7Zdl0c-CuTxbsCAxSqAHaEK?w=278&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
      location: 'Munich',
      genre: 'Oldies, Pop',
      website: 'https://www.br.de/radio/bayern1/index.html',
      slogan: 'Mein Tag - Mein Leben - Meine Musik',
};

const { tracks, loadType } = await client.poru.resolve({ query: searchedStation.stream });
```

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Rather interesting this stream! While the first URL has support for HTTP/2 -- being supported by NL -- it redirects to a page that doesn't have support to it, causing it to be stuck as for some reason, it doesn't emit "Protocol errors"
