### ISSUE TITLE
[BUG]: TrackException doesn't end tracks

### ISSUE THREAD

**Issue by Fyphen1223** [PerformanC/NodeLink#52]
### NodeLink version

Latest

### Description

When I try to seek audio with NodelInk, I encounter with this log:

```
[seek]: Received a request from client.
Params: "/v4/sessions/v8d065HO3cdmNtto/players/919809544648020008"
Headers: {"accept":"application/json, text/plain, /","content-type":"application/json","authorization":"REDACTED","user-agent":"axios/1.6.8","content-length":"18","accept-encoding":"gzip, compress, deflate, br","host":"REDACTED","connection":"keep-alive"}
Body: {"position":20000}
```

### Client

Shoukaku

### Steps to reproduce

Just seek YouTube vids

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnschooledGamer** [comment]
Alright, I'll verify the issue and confirm.

Thanks for reporting.

**Comment by UnschooledGamer** [comment]
@Fyphen1223 you probably have not installed ffmpeg, And NodeLink probably informed you with `TrackException` event.
Once installed seeking does work.

**Comment by Fyphen1223** [comment]
No, I already installed ffmpeg.

**Comment by ThePedroo** [comment]
We need further logging then, as only the request isn't enough

**Comment by Fyphen1223** [comment]
Gotchu, I will upload logs as soon as possible.

**Comment by ThePedroo** [comment]
Oops, closed due to a rebase

**Comment by Fyphen1223** [comment]
btw what kind of logs should I upload

**Comment by UnschooledGamer** [comment]
> btw what kind of logs should I upload

the `logs.txt` file generated by NodeLink

**Comment by Fyphen1223** [comment]
> > btw what kind of logs should I upload
> 
> the `logs.txt` file generated by NodeLink

k

**Comment by UnschooledGamer** [comment]
@Fyphen1223 Confirmed at our Discord Server That it's resolved/closed
