### ISSUE TITLE
[BUG]: Error: read ECONNRESET at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

### ISSUE THREAD

**Issue by Joniii11** [PerformanC/NodeLink#67]
### NodeLink version

V2.1.0 (Commit: https://github.com/PerformanC/NodeLink/commit/e443d1c0b9a43fff063477d27825fa19010a23d2)

### Description

This bug occures when disconnecting unexpectandly from a NodeLink Node.

This is the thrown error:
```bash
0|NodeLink  | node:events:496
0|NodeLink  |       throw er; // Unhandled 'error' event
0|NodeLink  |       ^
0|NodeLink  | Error: read ECONNRESET
0|NodeLink  |     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
0|NodeLink  | Emitted 'error' event on Socket instance at:
0|NodeLink  |     at emitErrorNT (node:internal/streams/destroy:169:8)
0|NodeLink  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
0|NodeLink  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
0|NodeLink  |   errno: -104,
0|NodeLink  |   code: 'ECONNRESET',
0|NodeLink  |   syscall: 'read'
0|NodeLink  | }
```

and crashes the whole node after this.

### Client

Poru (V5) modded (https://github.com/Joniii11/poru/tree/v5)

### Steps to reproduce

Connect yourself with a NodeLink and then just disconnect it aka CTRL + C'ing out of the program. Then this appears in console

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnschooledGamer** [comment]
@ThePedroo

**Comment by TehPigYT** [comment]
That means that the connection has been terminated, it is normal.

**Comment by UnschooledGamer** [comment]
> content

It shouldn't crashed I think 🤔.

**Comment by ThePedroo** [comment]
Unschooled is right, although the error is normal, NodeLink should've answered and handled it properly
