### ISSUE TITLE
[BUG]: TypeError: Invalid URL

### ISSUE THREAD

**Issue by Joniii11** [PerformanC/NodeLink#69]
### NodeLink version

V2.2.0 (4b4516e9cf26bb1f4dd35d5536d8efa8f74a0601)

### Description

0|NodeLink  | node:internal/url:797
0|NodeLink  |     this.#updateContext(bindingUrl.parse(input, base));
0|NodeLink  |                                    ^
0|NodeLink  | TypeError: Invalid URL
0|NodeLink  |     at new URL (node:internal/url:797:36)
0|NodeLink  |     at new ClientRequest (node:_http_client:135:30)
0|NodeLink  |     at Object.request (node:http:103:10)
0|NodeLink  |     at file:///home/ubuntu/NodeLink/src/utils.js:88:56
0|NodeLink  |     at new Promise (<anonymous>)
0|NodeLink  |     at http1makeRequest (file:///home/ubuntu/NodeLink/src/utils.js:85:10)
0|NodeLink  |     at file:///home/ubuntu/NodeLink/src/utils.js:937:31
0|NodeLink  |     at new Promise (<anonymous>)
0|NodeLink  |     at file:///home/ubuntu/NodeLink/src/utils.js:926:14
0|NodeLink  |     at file:///home/ubuntu/NodeLink/src/utils.js:871:25 {
0|NodeLink  |   code: 'ERR_INVALID_URL',
0|NodeLink  |   input: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">'
0|NodeLink  | }
0|NodeLink  | Node.js v20.13.1

### Client

Latest Poru on github.

### Steps to reproduce

Good question, just normally playing songs

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
I fixed some bugs in playlists, but couldn't replicate this. Do you mind providing encoded tracks that cause this?

**Comment by ThePedroo** [comment]
Maybe this was somehow fixed in last HLS related commits? Please re-open with more information if not.
