### ISSUE TITLE
Setting Volume On Play

### ISSUE THREAD

**Issue by clapann** [PerformanC/NodeLink#7]
file:///C:/Users/clap/Desktop/lava-node/NodeLink/src/connection/voiceHandler.js:409
    this.player.state.resource.volume.setVolume(volume / 100)
                               ^

TypeError: Cannot read properties of undefined (reading 'volume')

**Comment by ThePedroo** [comment]
Fixed on https://github.com/PerformanC/NodeLink/commit/2e63427f6074f7c4a62cb93d521340d3de2d0624

**Comment by clapann** [comment]
Issue still occurs.
