### ISSUE TITLE
[BUG]: NodeLink doesn't reset player position in player start event

### ISSUE THREAD

**Issue by Fyphen1223** [PerformanC/NodeLink#70]
### NodeLink version

Latest GH version

### Description

NodeLink doesn't reset the player position in the player start event on WS.
When overriding track, NodeLink should reset the position however, it doesn't reset and it's strange.

### Client

TsumiLink

### Steps to reproduce

Play some track, and override it without stopping it.

This is what it looks like:
```
{
  guildId: '919809544648020008',
  track: {
    encoded: 'QAAA0QMACldha2UgTWUgVXAABkF2aWNpaQAAAAAAA8aCABYwbnJSUDJiazE5ckxjMG9ya1dQUWsyAAEANWh0dHBzOi8vb3Blbi5zcG90aWZ5LmNvbS90cmFjay8wbnJSUDJiazE5ckxjMG9ya1dQUWsyAQBAaHR0cHM6Ly9pLnNjZG4uY28vaW1hZ2UvYWI2NzYxNmQwMDAwYjI3M2UxNGYxMWY3OTZjZWY5ZjlhODI2OTFhNwEADFNFVU03MTMwMTMyNgAHc3BvdGlmeQAAAAAAAAAA',
    info: {
      title: 'Wake Me Up',
      author: 'Avicii',
      length: 247426,
      identifier: '0nrRP2bk19rLc0orkWPQk2',
      isSeekable: true,
      isStream: false,
      uri: 'https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2',
      artworkUrl: 'https://i.scdn.co/image/ab67616d0000b273e14f11f796cef9f9a82691a7',
      isrc: 'SEUM71301326',
      sourceName: 'spotify',
      position: 0
    }
  },
  volume: 100,
  paused: false,
  filters: {},
  voice: {
    token: '',
    endpoint: 'discord.media:443',
    sessionId: ''
  },
  state: { time: 1716366133908, position: 8300, connected: false, ping: -1 }
}
```

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
I couldn't reproduce this -- when replacing a track it resets the voice statistics (frameStats), used for position.
