### ISSUE TITLE
[BUG]: Player's state information is weird

### ISSUE THREAD

**Issue by Fyphen1223** [PerformanC/NodeLink#74]
### NodeLink version

https://github.com/PerformanC/NodeLink/commit/9dcd5a762e99d7aaceae6f3148afe0262ac98bb7

### Description

When the player is paused, the player's state information goes wrong.
It says it's not connected.

### Client

TsumiLink

### Steps to reproduce

Play music -> Pause it -> And then check the data of the player

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnschooledGamer** [comment]
I don't remember was it reported before?. Nevermind I'll check the issue and have an update here later.

**Comment by Fyphen1223** [comment]
@UnschooledGamer [this issue](https://github.com/PerformanC/NodeLink/issues/72)?
I thought this was because of ffmpeg but seems like not...

**Comment by UnschooledGamer** [comment]
> @UnschooledGamer [this issue](https://github.com/PerformanC/NodeLink/issues/72)?
> I thought this was because of ffmpeg but seems like not...

Oh, I'll test later with raw clients(postman/insomnia) 😉.

**Comment by Fyphen1223** [comment]
> > @UnschooledGamer [this issue](https://github.com/PerformanC/NodeLink/issues/72)?
> > I thought this was because of ffmpeg but seems like not...
> 
> Oh, I'll test later with raw clients(postman/insomnia) 😉.

Got it, thanks!

**Comment by UnschooledGamer** [comment]
Hey @Fyphen1223 ,

The issue has being verified and is confirmed to be an bug.

A [PR](https://github.com/PerformanC/NodeLink/pull/75) has being opened for an Fix to it.

Thank You.
