### ISSUE TITLE
[BUG]: Can't run my spotify playlist

### ISSUE THREAD

**Issue by quangloc24** [PerformanC/NodeLink#76]
### NodeLink version

2.2.0

### Description

[loadtrack]: Exception loading playlist from Spotify: Resource not found

my spotify playlist: https://open.spotify.com/playlist/3rZh64idjQ0Fiz7ggnr1Jw?si=8980a6fd4b42497b

### Client

riffy

### Steps to reproduce

Play the playlist -> return issue -> check console of nodelink

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnschooledGamer** [comment]
@quangloc24 Is the spotify playlist available to you? I clicked the link and it says `page not found`, Is it private?

**Comment by ThePedroo** [comment]
I guess he posted the wrong one, the one sent in the Discord was: https://open.spotify.com/playlist/3rZh64idjQ0Fiz7ggnr1Jw?si=558d71bc35514750&pt=520f046d220cc8a1d155451d766c4d6c

**Comment by quangloc24** [comment]
sorry my bad, my playlist isnt public so it cant play. Now it can, thanks
