### ISSUE TITLE
[FR]: Letting clients to change the length of silence required to be detected as stop of speaking

### ISSUE THREAD

**Issue by Fyphen1223** [PerformanC/NodeLink#79]
### Description

Letting clients change the length of silence required to be detected as a stop of speaking.
D.js does provide such features, so it's technically client-side...

### Reason

It is useful.

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Already implemented.
