### ISSUE TITLE
[BUG]: NL sends too frequent startSpeakingEvent AGAIN

### ISSUE THREAD

**Issue by Fyphen1223** [PerformanC/NodeLink#88]
### NodeLink version

https://github.com/PerformanC/NodeLink/commit/be76e1ecd40afae292a7412f5e6ea1c2dff1535e

### Description

The title says everything

### Client

TsumiLink

### Steps to reproduce

Just record your voice.
It often sends two or three startSpeakingEvent.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Fixed in https://github.com/PerformanC/NodeLink/commit/be76e1ecd40afae292a7412f5e6ea1c2dff1535e.
